import type { NextPage } from "next";
import Head from "next/head";
import { NextSeo } from "next-seo";
import styles from "@styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
        <NextSeo description="A starter pack to build website with Next.js + Strapi" nofollow={false} />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">next-strapi-tailwind-starter</a>
        </h1>
        <div className={styles.grid}>
          <a className={styles.card} href="https://nextjs.org/docs">
            <h2>Next.js Docs &rarr;</h2>
          </a>
          <a className={styles.card} href="https://tailwindcss.com/docs/">
            <h2>Tailwind Docs &rarr;</h2>
          </a>
          <a className={styles.card} href="https://nextjs.org/docs">
            <h2>Strapi Docs &rarr;</h2>
          </a>

          <a
            className={styles.card}
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          >
            <h2>Deploy with vercel &rarr;</h2>
          </a>
        </div>
        {/* <div>
          <p>What you got:</p>
          <ul>
            <li>Next.js</li>
            <li>Tailwind</li>
            <li>Strapi</li>
            <li>Atomic Design</li>
          </ul>
        </div> */}
      </main>
    </div>
  );
};

export default Home;
