import type { NextPage } from "next";
import Head from "next/head";
import { NextSeo } from "next-seo";
import styles from "@styles/Home.module.css";
import { useContent } from "~/lib/content";

const Home: NextPage = () => {
  const { content } = useContent();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
        <NextSeo description="A starter pack to build website with Next.js + Strapi" nofollow={false} />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">next-strapi-tailwind-starter</a>
        </h1>
        <div className={styles.grid}>
          <a className={styles.card} href="https://nextjs.org/docs">
            <h2>Next.js Docs &rarr;</h2>
          </a>
          <a className={styles.card} href="https://tailwindcss.com/docs/">
            <h2>Tailwind Docs &rarr;</h2>
          </a>
          <a className={styles.card} href="https://nextjs.org/docs">
            <h2>Strapi Docs &rarr;</h2>
          </a>

          <a
            className={styles.card}
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          >
            <h2>Deploy with vercel &rarr;</h2>
          </a>
        </div>
        {/* <div>
          <p>What you got:</p>
          <ul>
            <li>Next.js</li>
            <li>Tailwind</li>
            <li>Strapi</li>
            <li>Atomic Design</li>
          </ul>
        </div> */}
        <div>
          <h3>
            This content managed by Strapi. Visit <a href="http://localhost:1337/admin">http://localhost:1337/admin</a>
          </h3>
          <table className="table-auto">
            <thead className="border-b dark:border-slate-600 font-medium p-4 pl-8 pt-0 pb-3 text-slate-400 dark:text-slate-200 text-left">
              <tr>
                <th>Key</th>
                <th>Value</th>
              </tr>
            </thead>
            <tbody>
              {Object.keys(content).map((key) => (
                <tr key={key}>
                  <td className="border-b border-slate-100 dark:border-slate-700 p-4 pl-8 text-slate-500 dark:text-slate-400 text-left">
                    {key}
                  </td>
                  <td className="border-b border-slate-100 dark:border-slate-700 p-4 pl-8 text-slate-500 dark:text-slate-400 text-left">
                    {content[key]}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </main>
    </div>
  );
};

export default Home;
